/**
 * The palettes a visitor is allowed to be drawn in.
 *
 * `hello` carries a palette string straight off the wire, and it ends up in every other
 * visitor's `Presence` and from there into a CSS custom property. An allowlist is the whole
 * defence: without it this is a string a stranger chose being handed to everyone else's
 * renderer, and "the client will sanitise it" is not a defence the client can offer on behalf
 * of other clients.
 *
 * **Derived from the design system's own manifest, not written out here.** This file used to
 * carry a hand-written list, and it drifted from the real palettes in precisely the way a
 * hand-written list always does. The symptom was the worst kind: the server closed every
 * socket with 1008 the moment a visitor said which palette they were in, including the default
 * one the page ships with, so the sky worked perfectly in every unit test and was unusable in
 * a browser. A list that has to be kept in step with another list will not be.
 *
 * `src/theme/palettes.json` is vendored from yozora and regenerated by its vendor script, so
 * adding a palette there adds it here with no edit. Never edit the vendored file.
 */
import manifest from "../theme/palettes.json";

type ManifestRow = { id: string; label: string; accent: string; scheme: "light" | "dark" };

/**
 * Loud rather than lenient. An empty or malformed manifest would otherwise produce an empty
 * allowlist, which refuses every palette including the default, and the page would look exactly
 * like the bug this file was rewritten to fix.
 */
function idsFrom(rows: unknown): readonly string[] {
  if (!Array.isArray(rows) || rows.length === 0) {
    throw new Error("palettes.json is empty or not an array, so there is no allowlist to build");
  }
  return rows.map((row, i) => {
    const id = (row as ManifestRow)?.id;
    if (typeof id !== "string" || id.length === 0) {
      throw new Error(`palettes.json row ${i} has no id`);
    }
    return id;
  });
}

export const PALETTES: readonly string[] = idsFrom(manifest);

export type Palette = string;

/**
 * What an occupant is drawn in until they say otherwise, and the one palette every page in
 * this portfolio opens on. Asserted against the manifest rather than assumed, because a
 * default that is not on the allowlist is the same 1008 bug wearing a different hat.
 */
export const DEFAULT_PALETTE = "twilight-comet";
if (!PALETTES.includes(DEFAULT_PALETTE)) {
  throw new Error(`the default palette ${DEFAULT_PALETTE} is not in palettes.json`);
}

const ALLOWED: ReadonlySet<string> = new Set(PALETTES);

/**
 * Note the length check before the set lookup. `Set.has` on a 50 MB string is not free, and
 * the point of a validator is that the cheapest test runs first.
 */
export function isPalette(value: unknown): value is Palette {
  return typeof value === "string" && value.length <= 32 && ALLOWED.has(value);
}
