#!/usr/bin/env node
/**
 * Turn the HYG catalogue into the smallest thing that is still a real sky.
 *
 * Input is `hygdata_v40.csv` from the HYG Database, CC BY-SA 4.0, itself compiled from
 * Hipparcos, Yale Bright Star and Gliese. Output is `src/sky/stars.generated.ts`, committed,
 * so a build needs no network and the file that ships is the file that was reviewed.
 *
 * Run:  node scripts/stars.mjs path/to/hygdata_v40.csv
 *
 * Two decisions, both about honesty rather than size:
 *
 * **Magnitude 6.5 is the cut, because that is the naked eye limit.** Not a number picked to
 * hit a file size. The sky this draws is the sky a person standing outside on a clear night
 * could see, which is the only cut that matches what the rest of the page claims to be.
 *
 * **Quantised, and the quantisation is stated.** Right ascension and declination go to 16 bits,
 * which is about 20 arcseconds and 10 arcseconds respectively, far finer than a star is drawn.
 * Magnitude and colour index go to 8 bits. This is a rendering format and the panel says so;
 * it is not a claim that Hipparcos measured to that precision, it is a claim that this file
 * stores what it needs to place a dot.
 */
import { readFileSync, writeFileSync } from "node:fs";

const MAG_LIMIT = 6.5;
const src = process.argv[2];
if (!src) { console.error("usage: node scripts/stars.mjs <hygdata csv>"); process.exit(1); }

const lines = readFileSync(src, "utf8").split("\n");
const head = lines[0].split(",").map((h) => h.replace(/"/g, ""));
const col = (n) => { const i = head.indexOf(n); if (i < 0) throw new Error(`no column ${n}`); return i; };
const [iRa, iDec, iMag, iCi, iProper, iCon] = ["ra", "dec", "mag", "ci", "proper", "con"].map(col);

/** Split a CSV row, respecting the quoted fields HYG uses for names. */
function cells(line) {
  const out = []; let cur = ""; let q = false;
  for (const ch of line) {
    if (ch === '"') q = !q;
    else if (ch === "," && !q) { out.push(cur); cur = ""; }
    else cur += ch;
  }
  out.push(cur); return out;
}

const stars = [];
for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  if (!line) continue;
  const c = cells(line);
  const mag = Number(c[iMag]);
  if (!Number.isFinite(mag) || mag > MAG_LIMIT) continue;
  const ra = Number(c[iRa]);      // hours, 0..24
  const dec = Number(c[iDec]);    // degrees, -90..90
  if (!Number.isFinite(ra) || !Number.isFinite(dec)) continue;
  if (ra === 0 && dec === 0 && c[iProper] === "Sol") continue; // the Sun is not a night sky object
  const ci = Number(c[iCi]);
  stars.push({ ra, dec, mag, ci: Number.isFinite(ci) ? ci : 0.6, proper: c[iProper] || "", con: c[iCon] || "" });
}
stars.sort((a, b) => a.mag - b.mag);

// Six bytes a star: ra u16, dec i16, mag u8, colour index u8.
const buf = new Uint8Array(stars.length * 6);
const view = new DataView(buf.buffer);
stars.forEach((s, n) => {
  const o = n * 6;
  view.setUint16(o, Math.round((s.ra / 24) * 65535));
  view.setInt16(o + 2, Math.round((s.dec / 90) * 32767));
  view.setUint8(o + 4, Math.max(0, Math.min(255, Math.round((s.mag + 2) * 30))));
  view.setUint8(o + 5, Math.max(0, Math.min(255, Math.round((s.ci + 0.4) * 100))));
});

/** The named ones, for the panel. Only stars with a real proper name, brightest first. */
const named = stars
  .map((s, index) => ({ ...s, index }))
  .filter((s) => s.proper)
  .slice(0, 120)
  .map((s) => [s.index, s.proper, s.con]);

const b64 = Buffer.from(buf).toString("base64");
writeFileSync(
  new URL("../src/sky/stars.generated.ts", import.meta.url),
  `// Generated by scripts/stars.mjs. Do not edit.
//
// Source: the HYG Database, CC BY-SA 4.0, https://github.com/astronexus/HYG-Database
// compiled from Hipparcos, the Yale Bright Star Catalogue and Gliese.
//
// ${stars.length} stars to magnitude ${MAG_LIMIT}, the naked eye limit. Six bytes each:
// right ascension u16 over 0..24h, declination i16 over -90..90, magnitude u8 as (mag+2)*30,
// colour index u8 as (ci+0.4)*100.

export const STAR_COUNT = ${stars.length};
export const STAR_MAG_LIMIT = ${MAG_LIMIT};
export const STAR_BYTES = "${b64}";
/** [index, proper name, constellation] for the brightest named stars. */
export const STAR_NAMES: readonly (readonly [number, string, string])[] = ${JSON.stringify(named)};
`,
);
console.log(`${stars.length} stars to magnitude ${MAG_LIMIT}, ${(buf.length / 1024).toFixed(1)} kB raw, ${(b64.length / 1024).toFixed(1)} kB base64, ${named.length} named`);
